### ISSUE TITLE
Latest vscode update (?) causing undefined on window.activeTextEditor

### ISSUE THREAD

**Issue by jdivy** [RobHolme/vscode-hl7tools#18]
https://code.visualstudio.com/api/references/vscode-api#window  According to this documentation, window.activeTextEditor _may_ be undefined.  I'm not sure why this is all of a sudden throwing an error when trying to execute the "Check required fields" action on this extension, but it's for sure blowing up in the ParseDelimiters function https://github.com/RobHolme/vscode-hl7tools/blob/2a48977ddcf80c77b01b914bd8ea317127f9db9d/lib/common.js#L26

I have an active editor (tried both saved and unsaved) so that's why it's somewhat confusing to me, but in any case seems like something that could be handled?

> 2020-04-14 12:48:01.601] [exthost] [error] Activating extension RobHolme.hl7tools failed due to an error:
[2020-04-14 12:48:01.604] [exthost] [error] TypeError: Cannot read property 'document' of undefined
	at Object.ParseDelimiters (c:\Users\Somebody\.vscode\extensions\robholme.hl7tools-1.11.0\lib\common.js:26:48)
	at activate (c:\Users\Somebody\.vscode\extensions\robholme.hl7tools-1.11.0\extension.js:101:22)
	at Function._callActivateOptional (c:\Users\Somebody\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:788:244)
	at Function._callActivate (c:\Users\Somebody\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:787:909)
	at c:\Users\Somebody\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:786:960
	at async Promise.all (index 0)
	at async h.$activate (c:\Users\Somebody\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:793:297)

**Comment by jdivy** [comment]
Probably a false alarm...looks like I had two vscode windows open and the one I was trying to execute this plugin inside had not closed/reopened to refresh (though I did uninstall/reinstall the plugin)

**Comment by jdivy** [comment]
I guess it still could be handled specifically but all is well now.

**Comment by RobHolme** [comment]
Thanks for the detailed submission - I'll take a look at improving this when I get a some free time on a weekend. It looks like I've made the assumption that window.activeTextEditor would return a valid reference numerous times throughout the extension.
