### ISSUE TITLE
Webview - Favourite Description error

### ISSUE THREAD

**Issue by myName-scor** [RobHolme/vscode-hl7tools#26]
First of all, thank you for the great extension.
In your new version 1.14 I have the problem with sending messages, the webview can not read the values of the settings.json.

I tried several times to set the values of the favorites, also removed the setting. It always ran into this error.

`2022-07-22 22:20:41.158] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'Description')
	at ExtensionPreferences.get FavouriteRemoteHosts [as FavouriteRemoteHosts] (c:\Users\XXX\.vscode\extensions\robholme.hl7tools-1.14.0\src\ExtensionPreferences.js:35:47)
	at c:\Users\XXX\.vscode\extensions\robholme.hl7tools-1.14.0\extension.js:338:54
	at o._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:62871)
	at o.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63575)
	at s._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13708)
	at s._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13390)
	at s._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12159)
	at s._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10853)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8957
	at w.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at a.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:34679
	at w.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at a.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
	at r._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23563)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21097
	at w.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15807)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:14937
	at Socket.R (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:13763)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) hl7tools.SendMessage {"value":"RobHolme.hl7tools","_lower":"robholme.hl7tools"}`
![VSCODE-HL7Tool-Issue](https://user-images.githubusercontent.com/43367545/180559978-8230450b-2810-49a8-841e-34db70eb5cb8.jpg)

**Comment by RobHolme** [comment]
I wasn't able to reproduce the issue by copying the settings you provided. The settings you provided look valid, I couldn't spot any obvious issues. However I could reproduce the error when the setting was empty or removed. I've updated the extension and republished as v1.14.1. 

This should prevent the error from occurring when the favourite list is not populated - however I suspect there is still a separate issue preventing your settings being read. i.e. the error should no longer be reported, but the favourite may still not be populated. 

Can you let me know your results of testing this with v1.14.1

**Comment by myName-scor** [comment]
Hi RobHolme,
thanks for the quick response. The problem seems to be solved, thank you very much. Now the value also shows up in the favorites list. And a transmission on a target system works.
![VSCODE-HL7Tool-Issue-2](https://user-images.githubusercontent.com/43367545/180593678-45969e21-d40f-4b38-b952-a4665d7177d8.jpg)

**Comment by RobHolme** [comment]
Thanks for testing. I've made a further change (v1.14.2) that does same basic validation on the favourites provided in the settings. If any favourite entries are missing a required property they will be skipped - remaining favourites that pass validation will continue to be added to the drop list.

**Comment by myName-scor** [comment]
Hi, tested the version and found no problems. Well done and thanks
